import { useEffect, useState } from "react";
import { registerSW } from "virtual:pwa-register";
import { Button } from "@/components/ui/button";

/**
 * Customer-facing reliability: prompts users to refresh when a new service worker
 * version is available. This prevents stale cached UI (e.g., duplicated cards)
 * persisting after deployment.
 */
export function PwaUpdateBanner() {
  const [needRefresh, setNeedRefresh] = useState(false);
  const [updating, setUpdating] = useState(false);

  useEffect(() => {
    // Registers (or hooks into) the SW generated by vite-plugin-pwa.
    const updateSW = registerSW({
      immediate: true,
      onNeedRefresh() {
        setNeedRefresh(true);
      },
    });

    // Proactively check for updates on load.
    // (Some browsers can be slow to re-check unless prompted.)
    void updateSW(false);
  }, []);

  if (!needRefresh) return null;

  return (
    <div className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur">
      <div className="mx-auto flex max-w-4xl items-center justify-between gap-3 px-4 py-3">
        <div className="min-w-0">
          <p className="text-sm font-medium text-foreground">Update available</p>
          <p className="text-xs text-muted-foreground">
            Refresh to load the latest version of your customer portal.
          </p>
        </div>
        <Button
          size="sm"
          onClick={async () => {
            try {
              setUpdating(true);
              // Reloads the page after activating the new SW.
              const updateSW = registerSW({ immediate: true });
              await updateSW(true);
            } finally {
              setUpdating(false);
            }
          }}
          disabled={updating}
        >
          {updating ? "Refreshing…" : "Refresh"}
        </Button>
      </div>
    </div>
  );
}
